### PR TITLE
Redesigned PixHawk Board

### PR DESCRIPTION
**Pull request by dvarshney1**

### CODE REVIEW

**Comment by abrandemuehl** [comment]
Looks like some airwires still exist in the design. Can you fix them?

image

The airwire in between the headers indicates that the "ground planes" that they are on are not connected. You can probably solve this by adding vias (on the sidebar) and naming them "GND". This will connect the top ground plane to the bottom ground plane and hopefully connect those grounds.

The 'X' over the CAN_H pin indicates that it's not connected to the pin on the other side. If it isn't possible to get it connected, you can remove the CAN_H and CAN_L connections in the schematic file.

**Comment by abrandemuehl** [comment]
Another problem is the size of all your traces. You've made most of the 6 mils, which is extremely small. Can you make sure that all traces are at least 10mils wide?

**Comment by abrandemuehl** [comment]
This is a bit of a nitpick, but can you make sure to avoid kinks in the traces as much as possible?

For example:
image

The kink in PWM5 is not necessary and would shorten the trace if removed. In general you should avoid having turns in your traces, even if it isn't too important in low speed signals.

**Comment by dvarshney1** [comment]
Sure, I'll go over these changes and push it back for your review.

**Comment by abrandemuehl** [comment]
Closing in favor of #4

**Pull request closed without merging**
