### PR TITLE
Redone ESC boards

### PR DESCRIPTION
**Pull request by abrandemuehl**
Just opening this for @ShredNinjaJr

### CODE REVIEW

**Comment by abrandemuehl** [comment]
Can you make JP2 a 3 pin header? The hall effect sensor needs power, gnd and signal I think

**Comment by abrandemuehl** [comment]
Also, add holes for use to mount the board to the o-ring flange. You can find the hole locations here: http://docs.bluerobotics.com/wte/cad/WTE6-M-FLANGE-SEAL-R1.PNG

**Comment by abrandemuehl** [comment]
The traces going to the ESC's are currently 20 mils, but they should be as large as possible, since they might be taking up to 13-15A at once

**Comment by abrandemuehl** [comment]
Can you name all the traces? It's hard to figure out where they are going without names

**Comment by abrandemuehl** [comment]
You still need to put on places for us to connect the motors wires to. You have the ESC outputs going into the board, but no place for us to connect motors to

**Comment by abrandemuehl** [comment]
You need a battery input XT60 connector

**Comment by abrandemuehl** [comment]
Can you move the labels for the mosfets on the brd file so that the silkscreen doesn't overlap?

**Comment by vemulpt2** [comment]
- [x] JP2 to 3pin
- [x] Holes mounting
- [x] Names for traces
- [x] Trace width increase
- [x] Connect wires for motor/ESV
- [x] XT60
- [x] label overlap

- [ ] Add another 2x10 header
- [ ] Redo the kill switch

**Comment by abrandemuehl** [comment]
Actually, can you also add another pin to the 2x8 pwm header? We need something that will tell the rest of the sub that the kill switch is pressed. Ideally, it would be isolated from the ground and power lines of the motors, so something like a transistor between the pins might work.

**Comment by abrandemuehl** [comment]
Just make the header 2x10. It's easier to find ribbon cables that match

**Comment by abrandemuehl** [comment]
It looks good to me. You'll have to fix the conflict with auv.lbr, but you can do that by opening the master auv.lbr in a window, then doing a copy to library on all the parts in your auv.lbr that you made. Then just replace your auv.lbr with this one

**Comment by abrandemuehl** [comment]
If you have time, it would be nice if the optocoupler was surface mount, but it doesn't matter that much

**Comment by abrandemuehl** [comment]
I think this board is ready to be merged. Can you fix the conflicts with auv.lbr and then push it up? I'll merge it after that

**Comment by abrandemuehl** [comment]
- [x] Make the silkscreen on the bottom of the board not overlap.
- [x] Indicate positive and negative terminals on the esc VIN and GND
- [x] Make silkscreen on top layer not overlap (`smash` the fets and move the text around/delete value/name)
- [x] Label the pins on the output so we know which ones connect where
- [ ] Give names to the nets going to the output pins ( the ones coming out of the opto isolator) so that I know what they are

**Review by vemulpt2 — APPROVED** [review]

**Pull request merged**
